journal/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # VISITOR URL
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('privacy/', views.privacy, name='privacy'),
    path('upload/', views.upload, name='upload'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('comment/<int:post>/', views.comment, name='comment'),
    path('like/<int:selected_comment>/', views.like, name='like'),
    path('signal/<int:selected_comment>/', views.signal, name='signal'),
    path('reply/<int:selected_comment>/', views.reply, name='repondre'),
    path('lastArticles/', views.last_articles, name='lastArticles'),
    path('author/<int:selected_author_id>/', views.author, name='author'),
    path('videos/', views.videos, name='video'),
    path('video/<int:selected_video_id>/', views.video_show, name='video_show'),
    path('search/', views.search, name='search'),
    path('tag/<slug:tag_name>/', views.tag, name='tag'),

    # JOURNALIST URL
    path('journalist/', views.journalist, name='journalist'),
    path('journalist/profile/', views.journalist_profile, name='journalist_profile'),
    path('journalist/articles/', views.journalist_articles, name='journalist_articles'),
    path('journalist/create_article/', views.journalist_create_article, name='journalist_create_article'),
    path('journalist/update_article/<int:article_id>/', views.journalist_update_article,
         name='journalist_update_article'),
    path('journalist/cancel_article/', views.journalist_cancel_article, name="journalist_cancel_article"),
    path('journalist/cancel_video/', views.journalist_cancel_video, name="journalist_cancel_video"),
    path('journalist/videos/', views.journalist_video, name="journalist_videos"),
    path('journalist/create_video/', views.journalist_create_video, name='journalist_create_video'),
    path('journalist/update_video/<int:video_id>/', views.journalist_update_video,
         name='journalist_update_video'),

    # JOURNALIST AJAX URL
    path('journalist/upload_primary_image/', views.journalist_upload_primary_image,
         name='journalist_upload_primary_image'),
    path('journalist/update_primary_image/<int:article_id>/', views.journalist_update_primary_image,
         name='journalist_update_primary_image'),
    path('journalist/upload_primary_image_video/', views.journalist_upload_primary_image_video,
         name='journalist_upload_primary_image_video'),
    path('journalist/update_primary_image_video/<int:video_id>/', views.journalist_update_primary_image_video,
         name='journalist_update_primary_image_video'),
    path('journalist/upload_image/', views.journalist_upload_image, name='journalist_upload_image'),
    path('journalist/update_image/<int:article_id>/', views.journalist_update_image, name='journalist_update_image'),
    path('journalist/create_tag/', views.journalist_create_tag, name='journalist_create_tag'),
    path('journalist/delete_image/<int:image_id>/', views.journalist_delete_image, name="journalist_delete_image"),
    path('journalist/delete_image_update/<int:article_id>/<int:image_id>/', views.journalist_delete_image_update,
         name="journalist_delete_image_update"),

    # CATEGORY AND SHOW ARTICLE
    path('<slug:category_name>/<int:post>/', views.article_show, name='post'),
    path('<slug:category_name>/', views.category, name='category'),

]

stage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('journal/', include('journal.urls')),
    path('main/', include('main_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journal/models.py
import time
import os
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.utils.deconstruct import deconstructible

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


# For rename the file before save
@deconstructible
class PathAndRename(object):
    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        # eg: filename = 'my uploaded file.jpg'
        ext = filename.split('.')[-1]  # eg: 'jpg'
        uid = uuid.uuid4().hex[:10]  # eg: '567ae32f97'

        # eg: 'my-uploaded-file'
        new_name = '-'.join(filename.replace('.%s' % ext, '').split())

        # eg: 'my-uploaded-file_64c942aa64.jpg'
        renamed_filename = '%(new_name)s_%(uid)s.%(ext)s' % {'new_name': new_name, 'uid': uid, 'ext': ext}

        # eg: 'images/2017/01/29/my-uploaded-file_64c942aa64.jpg'
        return os.path.join(self.path, renamed_filename)


class Image(models.Model):
    description = models.CharField(max_length=255, blank=True, null=True)
    image_path = time.strftime('images/%Y/%m/%d')
    image = models.ImageField(upload_to=PathAndRename(image_path))
    date_publication = models.DateTimeField(auto_now_add=True)
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[ResizeToFill(262, 175)],
        format='JPEG',
        options={'quality': 100})
    image_video = ImageSpecField(
        source='image',
        processors=[ResizeToFill(600, 600)],
        format='JPEG',
        options={'quality': 100})

    def __str__(self):
        return self.image.name


class Journalist(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    tel = models.CharField(max_length=30)
    description = models.TextField(blank=True)
    date_creation = models.DateTimeField(auto_now_add=True, null=True)
    active = models.BooleanField(default=True)
    link = models.URLField(blank=True)
    facebook = models.URLField(blank=True)
    twitter = models.URLField(blank=True)
    youtube = models.URLField(blank=True)
    instagram = models.URLField(blank=True)
    google = models.URLField(blank=True)
    linkedin = models.URLField(blank=True)
    profile_picture = models.ForeignKey(Image, default=60, on_delete=models.SET(60))

    def __str__(self):
        return self.first_name.capitalize() + ' ' + self.last_name.upper()

    @staticmethod
    def email_list():
        return Journalist.objects.filter(active=True).values_list('email', flat=True)


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    color = models.CharField(max_length=30, default='#37474F')
    icon = models.CharField(max_length=30, null=True, blank=True)
    tab_home = models.CharField(max_length=50, default='tab1')

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField(blank=True, null=True)
    color = models.TextField(max_length=30, default='#37474F')

    def __str__(self):
        return self.name


class News(models.Model):
    title = models.CharField(max_length=255)
    small_title = models.CharField(null=True, blank=True, max_length=255)
    content = models.TextField(default='null')
    date_publication = models.DateTimeField(auto_now_add=True)
    view_number = models.IntegerField(default=0)
    resume = models.TextField(blank=True, null=True)
    comment_enable = models.BooleanField(default=True)
    share_enable = models.BooleanField(default=True)
    journalist = models.ForeignKey(Journalist, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.CASCADE)
    primary_image = models.ForeignKey(Image, on_delete=models.CASCADE, null=True)
    tag = models.ManyToManyField(Tag)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def add_view(self):
        self.view_number += 1
        self.save()

    def sorted_comment(self):
        return self.comment_set.all().order_by('-number_like')

    class Meta:
        verbose_name_plural = 'News'


class Video(News):
    video_url = models.URLField()
    data_merge = models.IntegerField(default=2)
    team_selection = models.BooleanField(default=False)


class ImageNews(Image):
    article = models.ForeignKey(News, on_delete=models.CASCADE, null=True, blank=True)


class AbstractComment(models.Model):
    full_name = models.CharField(max_length=50)
    date_publication = models.DateTimeField(auto_now_add=True)
    email = models.EmailField()
    message = models.TextField()
    number_like = models.IntegerField(default=0)

    def like(self):
        self.number_like += 1
        self.save()

    def dislike(self):
        self.number_like -= 1
        self.save()

    def __str__(self):
        return self.full_name

    class Meta:
        abstract = True


class Comment(AbstractComment):
    news = models.ForeignKey(News, on_delete=models.CASCADE)


class Answer(AbstractComment):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)


class Signal(models.Model):
    email = models.EmailField()
    cause = models.TextField()
    date_send = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email + '' + str(self.date_send.date())

    class Meta:
        abstract = True


class SignalComment(Signal):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)


class SignalAnswer(Signal):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)


class Newsletter(models.Model):
    email = models.EmailField(primary_key=True)
    register_date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.email


class CommentFilter(models.Model):
    word = models.CharField(max_length=50)

    def __str__(self):
        return self.word

    class Meta:
        verbose_name_plural = 'CommentsFilter'

journal/templates/journal/journalist/journalist-profile.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ journalist }} Profil
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'journal/css/journalist/journalist-profile.css' %}">
    <link rel="stylesheet" href="{% static 'journal/css/journalist/component.css' %}">
    <link rel="stylesheet" href="{% static 'journal/css/journalist/nav-journalist.css' %}">
{% endblock %}

{% block script %}
    $('#id_description').val("{{ journalist.description }}");
{% endblock %}

{% block content %}
    <!-- SECTION HEADER -->
    <div class="section header-info">
        <div class="container">
            <h2>Profil</h2>
            <!-- breadcrumb -->
            <ul class="article-breadcrumb pull-right">
                <li><a href="{% url 'index' %}">Accueil</a></li>
                <li><a href="{% url 'journalist' %}">Espace Journalistes</a></li>
                <li><a href="{% url 'journalist_profile' %}">Profil</a></li>
            </ul>
            <!-- /breadcrumb -->
        </div>
    </div>
    <!-- /SECTION HEADER -->
    <!-- NAV JOURNALIST -->
    <div class="container">
        <nav class="nav-journalist">
            <ul class="list-inline">
                <li><a href="{% url 'journalist_articles' %}">Articles</a></li>
                <li><a href="{% url 'journalist_videos' %}">Videos</a></li>
                <li><a href="#">Signals</a></li>
                <li><a href="{% url 'journalist_create_article' %}">Ajouter Article</a></li>
                <li><a href="{% url 'journalist_create_video' %}">Ajouter Video</a></li>
            </ul>
        </nav>
    </div>
    <!-- /NAV JOURNALIST -->
    <!-- /SECTION INFO -->
    <div class="container info-profile">
        <div class="row">
            <div class="col-lg-4 col-md-5">
                {% if message_image == 'success' %}
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        Photo de profil modifiée avec succès
                    </div>
                {% elif message_image == 'failed' %}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        Erreur lors de la mise à jour du photo de profil
                    </div>
                {% endif %}
                <div class="card card-user">
                    <div class="image">
                        <img src="{{ journalist.profile_picture.image_video.url }}" />
                    </div>
                    <div>
                        <form action="{% url 'journalist_profile' %}" method="post" class="js" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form_image.image }}
                            <label for="id_image"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17">
                                <path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"></path>
                            </svg> <span>Choisir un fichier&hellip;</span></label>
                            <input type="hidden" value="image" name="method">
                            <input type="submit" value="Modifier" class="profile-image-submit">
                        </form>
                    </div>
                    <div class="content">
                        <div class="author">
                            <h4 class="title">{{ journalist }}<br />
                                <a href="{% url 'author' journalist.id %}"><small>@{{ user.username }}</small></a>
                            </h4>
                        </div>
                        <p class="description text-center">
                            {{ journalist.description }}
                        </p>
                    </div>
                    <hr>
                    <div class="text-center">
                        <div class="row">
                            <div class="col-md-3 col-md-offset-1">
                                <h5>{{ journalist.news_set.count }}<br /><small>Posts</small></h5>
                            </div>
                            <div class="col-md-4">
                                <h5>{{ sum_views }}<br /><small>Vues</small></h5>
                            </div>
                            <div class="col-md-3">
                                <h5>{{ number_comment }}<br /><small>Comments</small></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 col-md-7">
                {% if message != 'null' %}
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        {% autoescape off  %}
                        {{ message }}
                        {% endautoescape %}
                    </div>
                {% endif %}
                <div class="card">
                    <div class="header">
                        <h4 class="title">Modifier votre profil</h4>
                    </div>
                    <div class="content">
                        <form action="{% url 'journalist_profile' %}" method="post">
                            {% if form.errors %}
                                <div class="alert alert-danger">
                                    <p style="font-size: 18px; font-weight: bold;">Veuillez corriger les erreurs ci dessous :</p>
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <p style="padding-left: 40px"><strong>{{ field.name }} : </strong>{{ error|escape }}</p>
                                    {% endfor %}
                                {% endfor %}
                                </div>
                            {% endif %}
                            {% csrf_token %}
                            <input type="hidden" value="profile" name="method">
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="email" name="email" value="{{ journalist.email }}" class="form-control border-input"
                                               placeholder="Email" maxlength="191" disabled>
                                        {{ form.j_email }}
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Username</label>
                                        {{ form.username }}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Telephone</label>
                                        {{ form.telephone }}
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Prénom</label>
                                        {{ form.first_name }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Nom</label>
                                        {{ form.last_name }}
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Website</label>
                                        {{ form.website }}
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Facebook</label>
                                        {{ form.facebook }}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Twitter</label>
                                        {{ form.twitter }}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Instagram</label>
                                        {{ form.instagram }}
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Youtube</label>
                                        {{ form.youtube }}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Google+</label>
                                        {{ form.google_plus }}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>LinkedIn</label>
                                        {{ form.linkedin }}
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>A Propos de moi</label>
                                        {{ form.description }}
                                    </div>
                                </div>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-danger btn-fill btn-wd">Update Profile</button>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'journal/js/journalist/custom-file-input.js' %}"></script>
{% endblock %}

journal/templates/journal/journalist/journalist.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ user }}, Journaliste à Newspaper
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'journal/css/journalist/journalist.css' %}">
{% endblock %}

{% block content %}
    <!-- SECTION HEADER -->
    <div class="section header-info">
        <div class="container">
            <h2>Espace Journalistes</h2>
            <!-- breadcrumb -->
            <ul class="article-breadcrumb pull-right">
                <li><a href="{% url 'index' %}">Accueil</a></li>
                <li><a href="{% url 'journalist' %}">Espace Journalistes</a></li>
            </ul>
            <!-- /breadcrumb -->
        </div>
    </div>
    <!-- /SECTION HEADER -->
    <!-- NAV JOURNALIST -->
    <div class="container">
        <nav class="nav-journalist">
            <ul class="list-inline">
                <li><a href="{% url 'journalist_profile' %}">Profil</a></li>
                <li><a href="{% url 'journalist_articles' %}">Articles</a></li>
                <li><a href="{% url 'journalist_videos' %}">Vidéos</a></li>
                <li><a href="#">Signals</a></li>
                <li><a href="{% url 'journalist_create_article' %}">Ajouter Article</a></li>
                <li><a href="{% url 'journalist_create_video' %}">Ajouter Video</a></li>
            </ul>
        </nav>
    </div>
    <!-- /NAV JOURNALIST -->
    <!-- INFO JOURNALIST -->
    <div class="section info-journalist">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <img src="{{ journalist.profile_picture.image_video.url }}" alt="{{ journalist.profile_picture.description }}">
                </div>
                <div class="col-md-4">
                    <h1>Bonjour {{ journalist }}</h1>
                    <p id="last-login">Dernière connexion : {{ user.last_login }}</p>
                    <p><i class="fa fa-file-text"></i> Nombre des articles ajoutés : <span>{{ statistic.number_news }}</span></p>
                    <p><i class="fa fa-video-camera"></i> Nombre de videos ajoutés : <span>{{ statistic.number_video }}</span> </p>
                    <p><i class="fa fa-eye"></i> Nombre total de vues des articles : <span>{{ statistic.news_views_sum }}</span> </p>
                    <p><i class="fa fa-eye"></i> Nombre total de vues des videos : <span>{{ statistic.video_views_sum }}</span></p>
                    <p><i class="fa fa-comment"></i> Nombre de commentaires sur vos post : <span>{{ statistic.number_comment }}</span></p>
                    <p><i class="fa fa-comment"></i> Nombre de commentaires que vous avez ajoutés :
                        <span>{{ statistic.self_comment_count }}</span></p>
                </div>
                <div class="col-md-5">
                    <div id="top-article">
                        <h3>Meilleur Article</h3>
                        <!-- TOP ARTICLE -->
                        <article class="article widget-article">
                            <div class="article-img">
                                <a href="{% url 'post' top_article.category.name top_article.id %}">
                                    <img src="{{ top_article.primary_image.image_thumbnail.url }}"
                                         alt="{{ top_article.primary_image.description }}">
                                </a>
                            </div>
                            <div class="article-body">
                                <h4 class="article-title"><a href="{% url 'post' top_article.category.name top_article.id %}">
                                    {{ top_article.small_title }}</a></h4>
                                <ul class="article-meta">
                                    <li><a href="{% url 'category' top_article.category %}" class="label">
                                        {{ top_article.category }}</a></li>
                                    <li><i class="fa fa-clock-o"></i> {{ top_article.date_publication }}</li>
                                    <li><i class="fa fa-eye"></i></li> {{ top_article.view_number }}
                                    <li><i class="fa fa-comments"></i> {{ top_article.comment_set.count }}</li>
                                </ul>
                            </div>
                        </article>
                        <!-- /ARTICLE -->
                    </div>
                    <div id="top-video">
                        <h3>Meilleur Video</h3>
                        <!-- TOP VIDEO -->
                        <article class="article widget-article">
                            <div class="article-img">
                                <a href="{% url 'post' top_article.category.name top_article.id %}">
                                    <img src="{{ top_video.primary_image.image_thumbnail.url }}"
                                         alt="{{ top_video.primary_image.description }}">
                                </a>
                            </div>
                            <div class="article-body">
                                <h4 class="article-title"><a href="{% url 'post' top_video.category.name top_article.id %}">
                                    {{ top_video.small_title }}</a></h4>
                                <ul class="article-meta">
                                    <li><a href="{% url 'video' %}" class="label">
                                        videos</a></li>
                                    <li><i class="fa fa-clock-o"></i> {{ top_video.date_publication }}</li>
                                    <li><i class="fa fa-eye"></i></li> {{ top_video.view_number }}
                                    <li><i class="fa fa-comments"></i> {{ top_video.comment_set.count }}</li>
                                </ul>
                            </div>
                        </article>
                        <!-- /VIDEO -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /INFO JOURNALIST -->
{% endblock %}